---
title: "Spam Detection: Update this title"
author: "Dennis Murray, Jared Law, Julien Bataillard, Cory Nichols"
date: "March 20th, 2018"
output:
  word_document:
    fig_caption: yes
section: MSDS 7333-403 - Quantifying the World - Case Study 5 (Unit 10)
---

## Abstract

## Introduction

## Literature Review

## Methods

## Results

## Conclusions and Future Work

## References

```{r load_libs, echo=FALSE, include=FALSE}
library(magrittr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(tm)
library(rpart)
library(caret)
library(mlr)
```

```{r setup, include=FALSE}
dir <- "~/DataScience/SMU/QTW/Unit10/CaseStudy/"
setwd(dir)
knitr::opts_knit$set(root.dir = dir)
knitr::opts_chunk$set(echo = FALSE)
```

```{r make, include=FALSE, cache=TRUE, eval=FALSE}
# get and clean data
#source("src/make.R")
```

```{r dtree}
spamPath <- "Data"

dirNames <- list.files(path = spamPath, full.names = TRUE)

fileNames <- list.files(dirNames[1], full.names = TRUE)

# pick random emails
idx = c(1:5, 15, 27, 68, 69, 329, 404, 427, 516, 852, 971)

# read in samples
sampleEmail = sapply(list.files(dirNames[1], full.names = TRUE)[idx], readLines)

# FUNC to split into header and body based on first blank line
splitMessage <- function(msg) {
  splitPoint = match("", msg) # find first blank line
  header = msg[1:(splitPoint-1)] # get header, will use this for attachments
  body = msg[ -(1:splitPoint) ] # get body
  return(list(header = header, body = body))
}

# split into header and body
sampleSplit <- lapply(sampleEmail, splitMessage)

# get headers
headerList = lapply(sampleSplit, function(msg) msg$header)

# process the header for feature engineering purposes
processHeader = function(header)
{
  # replace k:v for reading into read.dcf
  header[1] = sub("^From","Top-From:", header[1])
  
  # get k:v pairs, return in list
  headerMat = read.dcf(textConnection(header), all = TRUE)
  headerVec = unlist(headerMat)
  
  dupKeys = sapply(headerMat, function(x) length(unlist(x)))
  names(headerVec) = rep(colnames(headerMat), dupKeys)
  
  return(headerVec)
}

# get boundary id from email headers
getBoundary<- function(header) {
  boundaryIdx = grep("boundary=", header) # index boundary
  boundary = gsub('"', "", header[boundaryIdx]) # replace quotes
  gsub(".*boundary= *([^;]*);?.*", "\\1", boundary) # regexrepl with first group match
}

# pass in body and associated content type list
processAttach = function(body, contentType){
  # get length of body
  n = length(body)
  # get boundary given contentType string already extracted
  boundary = getBoundary(contentType)
 
  # where are starting boundary strings?
  bString = paste("--", boundary, sep = "")
  bStringLocs = which(bString == body)
  # where is ending boundary string?
  eString = paste("--", boundary, "--", sep = "")
  eStringLoc = which(eString == body)
  
  # if no ending string use length of body as ending boundary loc
  if (length(eStringLoc) == 0) eStringLoc = n
  
  # if beginning boundaries <= 1 then no attachments
  # take last line of message as last line of body
  if (length(bStringLocs) <= 1) {
    attachLocs = NULL
    msgLastLine = n
    # tiny little conditional
    if (length(bStringLocs) == 0) bStringLocs = 0
  } else {
    # else we have attachments, so establish locations
    # for all attachments - this just uses beginning and end
    # will get all attachment text
    attachLocs = c(bStringLocs[ -1 ],  eStringLoc)
    # identify message body last line
    msgLastLine = bStringLocs[2] - 1
  }
  
  # parse message body
  msg = body[ (bStringLocs[1] + 1) : msgLastLine] 
  if ( eStringLoc < n )
    # concatenate body and last lines
    msg = c(msg, body[ (eStringLoc + 1) : n ])
  
  # if we have attachments, parse them and get their types
  if ( !is.null(attachLocs) ) {
    # get length of each attachment
    attachLens = diff(attachLocs, lag = 1) 
    # pass beginning and ending positions to multivariate apply
    attachTypes = mapply(function(begL, endL) {
      # select the sections of body identified by attachLens
      # and find content type
      CTloc = grep("^[Cc]ontent-[Tt]ype", body[ (begL + 1) : (endL - 1)])
      # if no content type, no MIMEType
      if ( length(CTloc) == 0 ) {
        MIMEType = NA
      } else {
        CTval = body[ begL + CTloc[1] ]
        CTval = gsub('"', "", CTval )
        # get MIMEType
        MIMEType = sub(" *[Cc]ontent-[Tt]ype: *([^;]*);?.*", "\\1", CTval)   
      }
      return(MIMEType)
    }, 
    # pass in attachment locations to mapply
    attachLocs[-length(attachLocs)], attachLocs[-1])
  }
  
  # else if no attachments retrurn a list of the message body and no dataframe
  if (is.null(attachLocs)) return(list(body = msg, attachDF = NULL) )
  # else return a list of the body, and a dataframe detailing the lengths and types of attachments
  return(list(body = msg, 
              attachDF = data.frame(aLen = attachLens, 
                                    aType = unlist(attachTypes),
                                    stringsAsFactors = FALSE)))                                
}                       


readEmail = function(dirName) {
      # retrieve the names of files in directory
  fileNames = list.files(dirName, full.names = TRUE)
       # drop files that are not email
  notEmail = grep("cmds$", fileNames)
  if ( length(notEmail) > 0) fileNames = fileNames[ - notEmail ]

       # read all files in the directory
  lapply(fileNames, readLines, encoding = "latin1")
}

processAllEmail = function(dirName, isSpam = FALSE)
{
  # read all files in the directory
  messages = readEmail(dirName)
  fileNames = names(messages)
  n = length(messages)
  
  # split header from body
  eSplit = lapply(messages, splitMessage)
  rm(messages)

  # process header as named character vector
  headerList = lapply(eSplit, 
                      function(msg) processHeader(msg$header))
  
  # extract content-type key from each message
  contentTypes = sapply(headerList, 
                        function(header) header["Content-Type"])
  
  # extract the body from each message
  bodyList = lapply(eSplit, function(msg) msg$body)
  rm(eSplit)

  # determine which email have attachments, index
  hasAttach = grep("^ *multi", tolower(contentTypes))

  # get summary stats for attachments and the shorter body
  # index by those emails that have attachments
  attList = mapply(processAttach, # apply process Attach multivariate
                   bodyList[hasAttach],  # over bodies that have attachments
                   contentTypes[hasAttach],  # and their content types
                   SIMPLIFY = FALSE)
  
  # create a placeholder vector to store each df of attachments for
  # every email - if no attachment, index pos == NULL
  attachInfo = vector("list", length = n )
  attachInfo[ hasAttach ] = lapply(attList, 
                                  function(attEl) attEl$attachDF)
  
  # replace body listings with atachments with body from
  # process attach considering last lines
  bodyList[hasAttach] = lapply(attList, function(attEl) 
                                           attEl$body)
 
  # prepare return structure as a list of lists
  emailList = mapply(function(header, body, attach, isSpam) {
                      # return a list of lists for each message we can index into
                       list(isSpam = isSpam, header = header, 
                            body = body, attach = attach)
                     },
                     headerList, bodyList, attachInfo, 
                     rep(isSpam, n), SIMPLIFY = FALSE )
  names(emailList) = fileNames
  
  invisible(emailList)
}

# this results in a k:v pair for the header (processHeader)
# a list of lines of the body (splitMessage)
# a df of attachment types and attachment length (processAttach)
emailStruct <- mapply(processAllEmail, dirNames, isSpam = rep(c(FALSE,TRUE), 3:2))
emailStruct <- unlist(emailStruct, recursive = FALSE)
sampleStruct <- emailStruct[idx]
```

```{r d_tree_feature_engineering}

# create a list of functions
# apply list of functions to email structure
# make a DF of variables where column is one function
# and rows are emails, a lot of features below
funcList = list(
  isSpam =
    expression(msg$isSpam)
  ,
  isRe =
    function(msg) {
      # Can have a Fwd: Re:  ... but we are not looking for this here.
      # We may want to look at In-Reply-To field.
      "Subject" %in% names(msg$header) && 
        length(grep("^[ \t]*Re:", msg$header[["Subject"]])) > 0
    }
  ,
  numLines =
    function(msg) length(msg$body)
  ,
  bodyCharCt =
    function(msg)
      sum(nchar(msg$body))
  ,
  underscore =
    function(msg) {
      if(!"Reply-To" %in% names(msg$header))
        return(FALSE)
      
      txt <- msg$header[["Reply-To"]]
      length(grep("_", txt)) > 0  && 
        length(grep("[0-9A-Za-z]+", txt)) > 0
    }
  ,
  subExcCt = 
    function(msg) {
      x = msg$header["Subject"]
      if(length(x) == 0 || sum(nchar(x)) == 0 || is.na(x))
        return(NA)
      
      sum(nchar(gsub("[^!]","", x)))
    }
  ,
  subQuesCt =
    function(msg) {
      x = msg$header["Subject"]
      if(length(x) == 0 || sum(nchar(x)) == 0 || is.na(x))
        return(NA)
      
      sum(nchar(gsub("[^?]","", x)))
    }
  ,
  numAtt = 
    function(msg) {
      if (is.null(msg$attach)) return(0)
      else nrow(msg$attach)
    }
   
  ,
  priority =
    function(msg) {
      ans <- FALSE
      # Look for names X-Priority, Priority, X-Msmail-Priority
      # Look for high any where in the value
      ind = grep("priority", tolower(names(msg$header)))
      if (length(ind) > 0)  {
        ans <- length(grep("high", tolower(msg$header[ind]))) >0
      }
      ans
    }
  ,
  numRec =
    function(msg) {
      # unique or not.
      els = getMessageRecipients(msg$header)
      
      if(length(els) == 0)
        return(NA)
      
      # Split each line by ","  and in each of these elements, look for
      # the @ sign. This handles
      tmp = sapply(strsplit(els, ","), function(x) grep("@", x))
      sum(sapply(tmp, length))
    }
  ,
  perCaps =
    function(msg)
    {
      body = paste(msg$body, collapse = "")
      
      # Return NA if the body of the message is "empty"
      if(length(body) == 0 || nchar(body) == 0) return(NA)
      
      # Eliminate non-alpha characters and empty lines 
      body = gsub("[^[:alpha:]]", "", body)
      els = unlist(strsplit(body, ""))
      ctCap = sum(els %in% LETTERS)
      100 * ctCap / length(els)
    }
  ,
  isInReplyTo =
    function(msg)
    {
      "In-Reply-To" %in% names(msg$header)
    }
  ,
  sortedRec =
    function(msg)
    {
      ids = getMessageRecipients(msg$header)
      all(sort(ids) == ids)
    }
  ,
  subPunc =
    function(msg)
    {
      if("Subject" %in% names(msg$header)) {
        el = gsub("['/.:@-]", "", msg$header["Subject"])
        length(grep("[A-Za-z][[:punct:]]+[A-Za-z]", el)) > 0
      }
      else
        FALSE
    },
  
  # get hour of email
  hour =
    function(msg)
    {
      date = msg$header["Date"]
      if ( is.null(date) ) return(NA)
      # Need to handle that there may be only one digit in the hour
      locate = regexpr("[0-2]?[0-9]:[0-5][0-9]:[0-5][0-9]", date)
      
      if (locate < 0)
        locate = regexpr("[0-2]?[0-9]:[0-5][0-9]", date)
      if (locate < 0) return(NA)
      
      hour = substring(date, locate, locate+1)
      hour = as.numeric(gsub(":", "", hour))
      
      locate = regexpr("PM", date)
      if (locate > 0) hour = hour + 12
      
      locate = regexpr("[+-][0-2][0-9]00", date)
      if (locate < 0) offset = 0
      else offset = as.numeric(substring(date, locate, locate + 2))
      (hour - offset) %% 24
    }
  ,
  multipartText =
    function(msg)
    {
      if (is.null(msg$attach)) return(FALSE)
      numAtt = nrow(msg$attach)
      
      types = 
        length(grep("(html|plain|text)", msg$attach$aType)) > (numAtt/2)
    }
  ,
  hasImages =
    function(msg)
    {
      if (is.null(msg$attach)) return(FALSE)
      
      length(grep("^ *image", tolower(msg$attach$aType))) > 0
    }
  ,
  isPGPsigned =
    function(msg)
    {
      if (is.null(msg$attach)) return(FALSE)
      
      length(grep("pgp", tolower(msg$attach$aType))) > 0
    },
  perHTML =
    function(msg)
    {
      if(! ("Content-Type" %in% names(msg$header))) return(0)
      
      el = tolower(msg$header["Content-Type"]) 
      if (length(grep("html", el)) == 0) return(0)
      
      els = gsub("[[:space:]]", "", msg$body)
      totchar = sum(nchar(els))
      totplain = sum(nchar(gsub("<[^<]+>", "", els )))
      100 * (totchar - totplain)/totchar
    },
  subSpamWords =
    function(msg)
    {
      if("Subject" %in% names(msg$header))
        length(grep(paste(SpamCheckWords, collapse = "|"), 
                    tolower(msg$header["Subject"]))) > 0
      else
        NA
    }
  ,
  
  # of blanks in subject
  subBlanks =
    function(msg)
    {
      if("Subject" %in% names(msg$header)) {
        x = msg$header["Subject"]
        # should we count blank subject line as 0 or 1 or NA?
        if (nchar(x) == 1) return(0)
        else 100 *(1 - (nchar(gsub("[[:blank:]]", "", x))/nchar(x)))
      } else NA
    }
  ,
  noHost =
    function(msg)
    {
      # Or use partial matching.
      idx = pmatch("Message-", names(msg$header))
      
      if(is.na(idx)) return(NA)
      
      tmp = msg$header[idx]
      return(length(grep(".*@[^[:space:]]+", tmp)) ==  0)
    }
  ,
  
  # email end in #?
  numEnd =
    function(msg)
    {
      # If we just do a grep("[0-9]@",  )
      # we get matches on messages that have a From something like
      # " \"marty66@aol.com\" <synjan@ecis.com>"
      # and the marty66 is the "user's name" not the login
      # So we can be more precise if we want.
      x = names(msg$header)
      if ( !( "From" %in% x) ) return(NA)
      login = gsub("^.*<", "", msg$header["From"])
      if ( is.null(login) ) 
        login = gsub("^.*<", "", msg$header["X-From"])
      if ( is.null(login) ) return(NA)
      login = strsplit(login, "@")[[1]][1]
      length(grep("[0-9]+$", login)) > 0
    },
  
  # subject is caps
  isYelling =
    function(msg)
    {
      if ( "Subject" %in% names(msg$header) ) {
        el = gsub("[^[:alpha:]]", "", msg$header["Subject"])
        if (nchar(el) > 0) nchar(gsub("[A-Z]", "", el)) < 1
        else FALSE
      }
      else
        NA
    },
  # fwd pct of message
  forwards =
    function(msg)
    {
      x = msg$body
      if(length(x) == 0 || sum(nchar(x)) == 0)
        return(NA)
      
      ans = length(grep("^[[:space:]]*>", x))
      100 * ans / length(x)
    },
  
  isOrigMsg =
    function(msg)
    {
      x = msg$body
      if(length(x) == 0) return(NA)
      
      length(grep("^[^[:alpha:]]*original[^[:alpha:]]+message[^[:alpha:]]*$", 
                  tolower(x) ) ) > 0
    },
  
  isDear =
    function(msg)
    {
      x = msg$body
      if(length(x) == 0) return(NA)
      
      length(grep("^[[:blank:]]*dear +(sir|madam)\\>", 
                  tolower(x))) > 0
    },
  isWrote =
    function(msg)
    {
      x = msg$body
      if(length(x) == 0) return(NA)
      
      length(grep("(wrote|schrieb|ecrit|escribe):", tolower(x) )) > 0
    },
  avgWordLen =
    function(msg)
    {
      txt = paste(msg$body, collapse = " ")
      if(length(txt) == 0 || sum(nchar(txt)) == 0) return(0)
      
      txt = gsub("[^[:alpha:]]", " ", txt)
      words = unlist(strsplit(txt, "[[:blank:]]+"))
      wordLens = nchar(words)
      mean(wordLens[ wordLens > 0 ])
    }
  ,
  numDlr =
    function(msg)
    {
      x = paste(msg$body, collapse = "")
      if(length(x) == 0 || sum(nchar(x)) == 0)
        return(NA)
      
      nchar(gsub("[^$]","", x))
    }
)

getMessageRecipients =
  function(header)
  {
    c(if("To" %in% names(header))  header[["To"]] else character(0),
      if("Cc" %in% names(header))  header[["Cc"]] else character(0),
      if("Bcc" %in% names(header)) header[["Bcc"]] else character(0)
    )
  }

SpamCheckWords =
  c("viagra", "pounds", "free", "weight", "guarantee", "million", 
    "dollars", "credit", "risk", "prescription", "generic", "drug",
    "financial", "save", "dollar", "erotic", "million", "barrister",
    "beneficiary", "easy", 
    "money back", "money", "credit card")


# placeholder DF to capture variables
# created by funcList below
createDerivedDF =
function(email = emailStruct, operations = funcList, 
         verbose = FALSE)
{
  els = lapply(names(operations),
               function(id) {
                 if(verbose) print(id)
                 e = operations[[id]]
                 v = if(is.function(e)) 
                        sapply(email, e)
                      else 
                        sapply(email, function(msg) eval(e)) # if expression, evaluate it
                 v
         })

   df = as.data.frame(els)
   names(df) = names(operations)
   invisible(df)
}

emailDF <- createDerivedDF(emailStruct)
```

```{r eda, include=FALSE}

# basic EDA stuff
isSpamLabels <- emailDF$isSpam

boxplot(log(1+emailDF$perCaps) ~emailDF$isSpam)
qqplot((1+log(emailDF[emailDF$isSpam==TRUE,]$perCaps)), (1+log(emailDF[emailDF$isSpam==FALSE,]$perCaps)))
table(emailDF$numAtt, emailDF$isSpam)

# spam typically has no reply.
colM = c("#E41A1C80", "#377EB880")
isRe = factor(emailDF$isRe, labels=c("no Re:", "Re:"))
mosaicplot(table(isSpamLabels, isRe), main ="", xlab="", ylab="", color=colM)

# from email ending in numbers, ham usually has no ending #
fromNE = factor(emailDF$numEnd, labels=c("No #", "#"))
mosaicplot(table(isSpamLabels, fromNE), color=colM, main="", xlab="", ylab="")

# insert correlation matrix here for numerics?
# ANOVAs for comparing categorical and numeric?
# chi squared tests for categorical features independence from one another?
# LVQ for selecting optimal features in general?

```

```{r fit_dtree, include=FALSE}
#Read in data files
#Apply the Functions to create the features

# transform nominals and ordinals to factors with this function
setupRpart = function(data) {
  logicalVars = which(sapply(data, is.logical))
  facVars = lapply(data[ , logicalVars], 
                   function(x) {
                      x = as.factor(x)
                      levels(x) = c("F", "T")
                      x
                   })
  cbind(facVars, data[ , - logicalVars])
}

save(emailStruct, file="emailXX.rda")
emailDFrp = setupRpart(emailDF)

set.seed(418910) # set seed for reproducibility

spam = emailDFrp$isSpam == "T"
numSpam = sum(spam)
numHam = sum(!spam)

testSpamIdx = sample(numSpam, size = floor(numSpam/3))
testHamIdx = sample(numHam, size = floor(numHam/3))

testDF = 
  rbind( emailDFrp[emailDFrp$isSpam == "T", ][testSpamIdx, ],
         emailDFrp[emailDFrp$isSpam == "F", ][testHamIdx, ] )

trainDF =
  rbind( emailDFrp[emailDFrp$isSpam == "T", ][-testSpamIdx, ], 
         emailDFrp[emailDFrp$isSpam == "F", ][-testHamIdx, ])

# here's where we implement caret
# https://machinelearningmastery.com/tuning-machine-learning-models-using-the-caret-r-package/
# https://machinelearningmastery.com/feature-selection-with-the-caret-r-package/
# https://github.com/topepo/caret/blob/master/RegressionTests/Code/rpart.R
# https://machinelearningmastery.com/compare-models-and-select-the-best-using-the-caret-r-package/
# https://mlr-org.github.io/mlr-tutorial/devel/html/tune/index.html

rpartFit = rpart(isSpam ~ ., 
                 data = trainDF, 
                 method = "class")

library(rpart.plot)
prp(rpartFit, extra=1)
print(rpartFit)

#errs = sapply(rpartFit, function(preds) {
#                      typeI = sum(preds[ !spam ] == "T") / numHam
#                      typeII = sum(preds[ spam ] == "F") / numSpam
#                      c(typeI = typeI, typeII = typeII)
#                     })

predictions = predict(rpartFit, 
                      newdata = testDF[,names(testDF) !="isSpam"],
                      type="class")

predsForHam = predictions[testDF$isSpam == "F"]
summary(predsForHam)

# type 1 error rate (finding spam when none)
sum(predsForHam=="T")/length(predsForHam)


predsForSpam = predictions[testDF$isSpam == "T"]
summary(predsForSpam)

# type II error rate (not finding spam)
sum(predsForSpam == "F")/length(predsForSpam)

# params
complexityVals <- c(seq(0.00001, 0.1, length=25))

fits = lapply(complexityVals, function(x) {
  rpartObj = rpart(isSpam ~ ., data=trainDF,
                   method="class",
                   control=rpart.control(cp=x))
  predict(rpartObj,
          newData = testDF[, names(testDF) != "isSpam"],
          type= "class")
})

spam = testDF$isSpam == "T"
numSpam = sum(spam)
numHam = sum(!spam)

errs = sapply(fits, function(preds){
  typeI = sum(preds[!spam] == "T") / numHam
  typeII = sum(preds[spam] == "F") / numSpam
  c(typeI = typeI, typeII=typeII)
})


library(MLmetrics)
# preProc <- preProcess(method="bagImpute", trainDF)

# set up f1 summary metric
f1 <- function(data, lev = NULL, model = NULL) {
  f1_val <- F1_Score(y_pred = data$pred, y_true = data$obs, positive = lev[1])
  c(F1 = f1_val)
}

grid <- expand.grid(cp=c(0.01, 0.02, 0.05, 0.1, 0.5))

fitControl <- trainControl(method="cv", number=10, summaryFunction = f1)

rpFit <- train(            isSpam ~ .,
                           data = trainDF, 
                           method="rpart",
                           trControl = fitControl, 
                           na.action = na.omit,
                           tuneLength=5)

varImp(rpFit)
rpFit


trainDF$isSpam <- relevel(trainDF$isSpam, "T")

rpFitwGrid <- train(       isSpam ~ .,
                           data = trainDF, 
                           method="rpart",
                           trControl = fitControl, 
                           na.action = na.omit,
                           tuneGrid=grid)




# Create the learner
lrn = makeLearner("classif.rpart")

dat.task = makeClassifTask(id = "spam", 
                           data = trainDF, 
                           target = "isSpam", 
                           check.data = FALSE)

#https://cran.r-project.org/web/packages/mlr/vignettes/mlr.html
# using ML
# Define the model
resamp = makeResampleDesc("CV", iters = 10L, stratify = TRUE)
# Create the grid params
control.grid = makeTuneControlGrid() 
ps = makeParamSet(
     makeDiscreteParam("cp", values = c(0.00001, 0.001, 0.01, 0.1)),
     makeDiscreteParam("minsplit", values = c(1, 5, 10, 15))
     #makeDiscreteParam("maxdepth", values = c(2, 5, 10)))
      )
tuned = tuneParams(lrn, 
                   task = dat.task, 
                   resampling = resamp, 
                   control = control.grid, 
                   par.set = ps, measures = list(fnr, fpr))

```






```{r bayes_get_data, include=FALSE}
# RSpamData not available in R 3.4.3

spamPath <- "Data"

dirNames <- list.files(path = spamPath, full.names = TRUE)

fileNames <- list.files(dirNames[1], full.names = TRUE)

sapply(dirNames, function(x) length(list.files(x)))

# pick random emails
idx = c(1:5, 15, 27, 68, 69, 329, 404, 427, 516, 852, 971)

#sampleEmail = sapply(list.files(dirNames[1], full.names = TRUE)[idx], readLines)

# split into header and body
splitMessage <- function(msg) {
  splitPoint = match("", msg) # find first blank line
  header = msg[1:(splitPoint-1)] # get header, will use this for attachments
  body = msg[ -(1:splitPoint) ] # get body
  return(list(header = header, body = body))
}

sampleSplit <- lapply(sampleEmail, splitMessage)

# get headers
headerList = lapply(sampleSplit, function(msg) msg$header)

# get boundary id from multi-part email

getBoundary<- function(header) {
  boundaryIdx = grep("boundary=", header) # index boundary
  boundary = gsub('"', "", header[boundaryIdx]) # replace quotes
  gsub(".*boundary= *([^;]*);?.*", "\\1", boundary) # regexrepl with first group match
}

# pass boundary and body of each message
dropAttach = function(body, boundary){
  bString = paste("--", boundary, sep = "") 
  bStringLocs = which(bString == body)# find start locs for each section of body
  # -- is arbitrary
  
  if (length(bStringLocs) <= 1) return(body) # if no boundaries, give me back body
  
  eString = paste("--", boundary, "--", sep = "") # ending boundary string
  eStringLoc = which(eString == body) # ending string loc
  if (length(eStringLoc) == 0)  # if no ending string return first part of body
    return(body[ (bStringLocs[1] + 1) : (bStringLocs[2] - 1)])
  
  # otherwise get length of body
  n = length(body)
  # if ending boundary string < rows, return body + ending rows after ending boundary
  if (eStringLoc < n) 
     return( body[ c( (bStringLocs[1] + 1) : (bStringLocs[2] - 1), 
                    ( (eStringLoc + 1) : n )) ] )
  
  # finally, return body if no other conditions met
  return( body[ (bStringLocs[1] + 1) : (bStringLocs[2] - 1) ])
}

# clean up punctuation, numbers, spaces
cleanText =
function(msg)   {
  tolower(gsub("[[:punct:]0-9[:space:][:blank:]]+", " ", msg))
}

findMsgWords = 
function(msg, stopWords) {
 if(is.null(msg))
  return(character())

  # split and return vector of cleaned words
 words = unique(unlist(strsplit(cleanText(msg), "[[:blank:]\t]+")))
 
 # drop empty and 1 letter words
 words = words[ nchar(words) > 1]
 words = words[ !( words %in% stopWords) ]
 invisible(words)
}

processAllWords = function(dirName, stopWords)
{
  # read all files in a given directory
  fileNames = list.files(dirName, full.names = TRUE)
  # drop files that are not email
  notEmail = grep("cmds$", fileNames)
  
  if ( length(notEmail) > 0) fileNames = fileNames[ - notEmail ]

  # read all messages into a list
  messages = lapply(fileNames, readLines, encoding = "latin1")
  
  # split header and body for each message
  emailSplit = lapply(messages, splitMessage)
  # put body and header in own lists
  bodyList = lapply(emailSplit, function(msg) msg$body)
  headerList = lapply(emailSplit, function(msg) msg$header)
  # save some memory, kill emailSplit var
  rm(emailSplit)
  
  # determine which messages have attachments
  hasAttach = sapply(headerList, function(header) {
    CTloc = grep("Content-Type", header)
    if (length(CTloc) == 0) return(0)
    multi = grep("multi", tolower(header[CTloc])) 
    if (length(multi) == 0) return(0)
    multi # has attachment
  })
  
  # get indices for which messages have attachments
  hasAttach = which(hasAttach > 0)
  
  # find boundary strings for messages with attachments
  boundaries = sapply(headerList[hasAttach], getBoundary)
  
  # drop attachments from message bodies
  bodyList[hasAttach] = mapply(dropAttach, bodyList[hasAttach], 
                               boundaries, SIMPLIFY = FALSE)
  
  # extract words from body
  msgWordsList = lapply(bodyList, findMsgWords, stopWords)
  
  invisible(msgWordsList)
}

msgWordsList = lapply(dirNames, processAllWords, stopWords=stopWords)

numMsgs = sapply(msgWordsList, length)

# identify which messages are spam based on num Msgs
isSpam = rep(c(FALSE, FALSE, FALSE, TRUE, TRUE), numMsgs)

# list of vectors of cleaned words for each message
msgWordsList = unlist(msgWordsList, recursive = FALSE)
```

``` {r bayes_train_test_split, include=FALSE}
set.seed(418910)

numEmail = length(isSpam)
numSpam = sum(isSpam)
numHam = numEmail - numSpam

# take 1/3 of data for testing from each class spam ham
testSpamIdx = sample(numSpam, size =floor(numSpam/3))
testHamIdx = sample(numHam, size=floor(numHam/3))

# get word vectors from msgWordsList
# test
testMsgWords = c((msgWordsList[isSpam])[testSpamIdx],
                 (msgWordsList[!isSpam])[testHamIdx])

# train
trainMsgWords = c((msgWordsList[isSpam])[-testSpamIdx],
                 (msgWordsList[!isSpam])[-testHamIdx])

# get labels for train and test
testIsSpam = rep(c(TRUE, FALSE), 
                 c(length(testSpamIdx), length(testHamIdx)))

trainIsSpam = rep(c(TRUE, FALSE), 
                 c(numSpam - length(testSpamIdx), 
                   numHam - length(testHamIdx)))

```

```{r bayes_freq_table, include=FALSE}

computeFreqs <- function(wordsList, spam, bow = unique(unlist(wordsList))) {
   # create a matrix for spam, ham, and log odds
  wordTable = matrix(0.5, nrow = 4, ncol = length(bow), # default value is 0.5
                     dimnames = list(c("spam", "ham",  # name dimensions
                                        "presentLogOdds", 
                                        "absentLogOdds"),  bow))

  # build frequency table 
  # For each spam message, add 1 to counts for words in message
  counts.spam = table(unlist(lapply(wordsList[spam], unique)))
  wordTable["spam", names(counts.spam)] = counts.spam + .5

   # Similarly for ham messages
  counts.ham = table(unlist(lapply(wordsList[!spam], unique)))  
  wordTable["ham", names(counts.ham)] = counts.ham + .5  


   # Find the total number of spam and ham
  numSpam = sum(spam) # from T/F vector passed to func
  numHam = length(spam) - numSpam

  # Prob(word|spam) and Prob(word | ham)
  # compute probabilities for each word given spam or ham
  wordTable["spam", ] = wordTable["spam", ]/(numSpam + .5)
  wordTable["ham", ] = wordTable["ham", ]/(numHam + .5)
  
   # calculate log odds
  # log odds of presence
  wordTable["presentLogOdds", ] = 
     log(wordTable["spam",]) - log(wordTable["ham", ])
  # log odds of absence
  wordTable["absentLogOdds", ] = 
     log((1 - wordTable["spam", ])) - log((1 -wordTable["ham", ]))

  invisible(wordTable)
}

```


```{r bayes_classify, include=FALSE}

# use our frequency and odds table to classify new messages
computeMsgLLR = function(words, freqTable) 
{
       # Discards words not in training data.
  words = words[!is.na(match(words, colnames(freqTable)))]

       # Find which words are present
  present = colnames(freqTable) %in% words

  sum(freqTable["presentLogOdds", present]) +
    sum(freqTable["absentLogOdds", !present])
}

testLLR = sapply(testMsgWords, computeMsgLLR, trainTable)

tapply(testLLR, testIsSpam, summary)

pdf("SP_Boxplot.pdf", width = 6, height = 6)
spamLab = c("ham", "spam")[1 + testIsSpam]
boxplot(testLLR ~ spamLab, ylab = "Log Likelihood Ratio",
      #  main = "Log Likelihood Ratio for Randomly Chosen Test Messages",
        ylim=c(-500, 500))
dev.off()

typeIErrorRate = 
function(tau, llrVals, spam)
{
  classify = llrVals > tau
  sum(classify & !spam)/sum(!spam)
}

typeIErrorRate(0, testLLR,testIsSpam)

typeIErrorRate(-20, testLLR,testIsSpam)

typeIErrorRates = 
function(llrVals, isSpam) 
{
  o = order(llrVals)
  llrVals =  llrVals[o]
  isSpam = isSpam[o]

  idx = which(!isSpam)
  N = length(idx)
  list(error = (N:1)/N, values = llrVals[idx])
}

typeIIErrorRates = function(llrVals, isSpam) {
    
  o = order(llrVals)
  llrVals =  llrVals[o]
  isSpam = isSpam[o]
    
    
  idx = which(isSpam)
  N = length(idx)
  list(error = (1:(N))/N, values = llrVals[idx])
  }  

xI = typeIErrorRates(testLLR, testIsSpam)
xII = typeIIErrorRates(testLLR, testIsSpam)
tau01 = round(min(xI$values[xI$error <= 0.01]))
t2 = max(xII$error[ xII$values < tau01 ])

pdf("LinePlotTypeI+IIErrors.pdf", width = 8, height = 6)

library(RColorBrewer)
cols = brewer.pal(9, "Set1")[c(3, 4, 5)]
plot(xII$error ~ xII$values,  type = "l", col = cols[1], lwd = 3,
     xlim = c(-300, 250), ylim = c(0, 1),
     xlab = "Log Likelihood Ratio Values", ylab="Error Rate")
points(xI$error ~ xI$values, type = "l", col = cols[2], lwd = 3)
legend(x = 50, y = 0.4, fill = c(cols[2], cols[1]),
       legend = c("Classify Ham as Spam", 
                  "Classify Spam as Ham"), cex = 0.8,
       bty = "n")
abline(h=0.01, col ="grey", lwd = 3, lty = 2)
text(-250, 0.05, pos = 4, "Type I Error = 0.01", col = cols[2])

mtext(tau01, side = 1, line = 0.5, at = tau01, col = cols[3])
segments(x0 = tau01, y0 = -.50, x1 = tau01, y1 = t2, 
         lwd = 2, col = "grey")
text(tau01 + 20, 0.05, pos = 4,
     paste("Type II Error = ", round(t2, digits = 2)), 
     col = cols[1])

dev.off()

k = 5
numTrain = length(trainMsgWords)
partK = sample(numTrain)
tot = k * floor(numTrain/k)
partK = matrix(partK[1:tot], ncol = k)

testFoldOdds = NULL
for (i in 1:k) {
  foldIdx = partK[ , i]
  trainTabFold = computeFreqs(trainMsgWords[-foldIdx], trainIsSpam[-foldIdx])
  testFoldOdds = c(testFoldOdds, 
               sapply(trainMsgWords[ foldIdx ], computeMsgLLR, trainTabFold))
}

testFoldSpam = NULL
for (i in 1:k) {
  foldIdx = partK[ , i]
  testFoldSpam = c(testFoldSpam, trainIsSpam[foldIdx])
}

xFoldI = typeIErrorRates(testFoldOdds, testFoldSpam)
xFoldII = typeIIErrorRates(testFoldOdds, testFoldSpam)
tauFoldI = round(min(xFoldI$values[xFoldI$error <= 0.01]))
tFold2 = xFoldII$error[ xFoldII$values < tauFoldI ]

```
